### ISSUE TITLE
Need help with this project. 

### ISSUE THREAD

**Issue by hapishyguy** [Contact-IoT-Digital-Signage/kiosk-app#1]
Hi Tishihara,

Need help with this project. Can you help?
My email or my number?

Thanks
Harp

**Comment by taro-ishihara** [comment]
Is it your project that needs help?
I need more details.

**Comment by taro-ishihara** [comment]
You can send DM in discord too.
TARO#3381

**Comment by hapishyguy** [comment]
No Comment
